# Numpy?

Numpy = Numerical Python

## It is used for :
    a. Fast numerical computations
    b. working with arrays (instead of lists)
    c. Backbone of ML libraries (Pandas, Scikit-learn, TensorFlow)

## Why Numpy is fast :

    a. Written in C (backend)
    b. Uses contiguous memory
    c. Supports vectorization (no loops needed)


In [4]:
import numpy as np

a = np.array([1,2,3]) #using list to create numpy array
b = np.array((4,5,6)) #using tuple to create numpy array

print(a)
print(b)

[1 2 3]
[4 5 6]


## Multi-Dimensional Arrays

In [6]:
a = np.array([[1,2,3],(4,5,6)])

a

array([[1, 2, 3],
       [4, 5, 6]])

## Special Arrays

    np.zeroes
    np.ones
    np.empty

In [ ]:
specialzeros = np.zeros((3,2,3)) #creates a 3D array of shape (3,2,3) filled with zeroes

specialzeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
specialones = np.ones((3,5)) #creates a 2D array of shape (3,5) filled with ones

specialones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
specialempty = np.empty((2,3,2,1)) # creates 4D array of shape (2,3,2,1) filled with uninitialized values

# uninitialized values :: Numpy just grabs a chunk (garbage values) of memory and shows whatever values were already there.
# So the values in the array will be random and can be different each time you run the code.

specialempty

array([[[[1.10609794e-311],
         [3.16202013e-322]],

        [[0.00000000e+000],
         [0.00000000e+000]],

        [[1.78022341e-306],
         [2.74965760e+180]]],


       [[[9.96882109e-047],
         [2.98044854e+179]],

        [[6.64341995e-066],
         [7.24161406e+169]],

        [[4.18582871e-062],
         [1.25720792e-075]]]])

## Range Arrays

    np.arange
    np.linspace

In [ ]:
array = np.arange(0,10,2)

# creates a 1D array with (start,stop,step).
# start => included || stop => excluded || step => difference between each element in the array.

array

array([2, 4, 6, 8])

In [ ]:
arr = np.linspace(0,10,5)

# creates  1D Array with (start,stop,end)
# start => included || stop => included || end => number of elements in the array, and the values are equally spaced between start and stop.

arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Array Attributes

    arr.ndim => dimensions
    arr.shape => rows, columns
    arr.size => total elements
    a.dtype => data type

In [31]:
arr = np.array([[1,2,3],(4,5,6)])

print(f"dimensions :: {arr.ndim}")
print(f"Shape :: {arr.shape}")
print(f"Size :: {arr.size}")
print(f"Data type :: {arr.dtype}")

dimensions :: 2
Shape :: (2, 3)
Size :: 6
Data type :: int64
