## Indexing

    1D indexing
    2D indexing

In [3]:
import numpy as np

arronedim = np.array([1,2,3,4,5,6,7,8,9])

print(arronedim[0])
print(arronedim[-1])

1
9


In [7]:
arrtwodim = np.array([[1,2,3],(4,5,6)])

print(arrtwodim[0,1]) #2
print(arrtwodim[1,2]) #6

2
6


## Slicing

    1D slicing
    2D slicing

In [12]:
arronedim = np.array([1,2,3,4,5,6,7,8,9])

print(arronedim[2:5]) # print elements from index 2 to 4 (5 is excluded)
print(arronedim[:4]) # print elements from the beginning to index 3 (4 is excluded)
print(arronedim[::-1]) # print elements in reverse order

# [idx1,idx2] idx1=>included || idx2=>excluded

[3 4 5]
[1 2 3 4]
[9 8 7 6 5 4 3 2 1]


In [13]:
arrtwodim = np.array([[1,2,3],(4,5,6)])

print(arrtwodim[:,1]) # print all rows and column index 1 (2 and 5)
print(arrtwodim[1,:]) # print row index 1 and all columns (4,5,6)

#[row,column] ":" => all rows or all columns depending on its position.

[2 5]
[4 5 6]


## Fancy Indexing


In [18]:
a=  np.array([1,2,3,4,5])
print(a[[0,2,4]]) #fancy indexing allows us to use an array of indices to access multiple array elements at once.


[1 3 5]
