## Operations

### Basic Operations
    a + b
    a-b
    a*b
    a/b

### Scalar Operations

    #scalar is nothing but a single value
    #vector/array (Multiple Values)
    a * 2
    a + 10

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [3]:
a = np.array([[1,2,3],[4,5,6]])

print(a + 10)
print(a * 2)

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


### BROADCASTING

    👉 If shapes are different, NumPy tries to adjust automatically

🧠 CONDITION FOR BROADCASTING

    For each dimension (right → left):

    ✔ Dimensions are equal
    OR
    ✔ One of them is 1

In [7]:
a = np.array([1,2,3])   # (3,)
b = np.array([10])     # (1,)

print(a + b)          

[11 12 13]


In [ ]:
#(2D + 1D)

a = np.array([[1,2,3],
              [4,5,6]])   # (2,3)

b = np.array([10,20,30])  # (3,)

print(a+b)

[[11 22 33]
 [14 25 36]]


In [10]:
#Column Broadcasting


a = np.array([[1,2,3],
              [4,5,6]])   # (2,3)

b = np.array([[10],
              [20]])      # (2,1)

print(a+b)

[[11 12 13]
 [24 25 26]]


In [11]:
#NOT COMPATIBLE → ERROR

a = np.array([1,2,3])   # (3,)
b = np.array([4,5])     # (2,)

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 